### ISSUE TITLE
Condition greather then

### ISSUE THREAD

**Issue by wouterlambrechts** [alonrbar/easy-template-x-angular-expressions#4]
Hello,

I am not entirely familiar with Angular Expressions.
But do you guys happen to have an example, how I can manage to do this.

{#item.discount > 0} 
{/}
{#item.discount = 5}
{/}

**Comment by frankod19** [comment]
**The handler should be defined as follows:**
const handler = new TemplateHandler({
    scopeDataResolver: createResolver({}) as ScopeDataResolver 
});

**Use `==` for comparison instead of `=` for assignment.**
For example, use the following conditions:
{#item.discount > 0}
{/}
{#item.discount == 5}
{/}

**Comment by alonrbar** [comment]
Thank you @frankod19 for taking this 👍
